#!/bin/bash

function usage() {
  echo -e "\nUsage: $0 <directory>\n\nDirectory is where you cloned the repository, or use -c for the current dir.\n"
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

function link_file() {
  file=$1
  if [ -e ~/.$file ]; then
    echo "backing up original ~/.$file to ~/.$file.orig "
    mv ~/.$file ~/.$file.orig
  fi
  ln -s $BASEDIR/$file ~/.$file
  echo "Linking .$file"
}

function setup() {
  files=(bashrc bash_aliases bash_gitprompt bash_profile bash_prompt)
  for f in ${files[@]}; do
    link_file ${f}
  done
}

while getopts "c" optname
  do
    case "$optname" in
      "c")
        echo -e "Using current directory.. \n"
        BASEDIR=$(pwd)
        setup
        ;;

      ":")
        echo "Using the supplied directory"
        BASEDIR=$1
        setup
        ;;
    esac
  done
